export const subscription = {
  id: 42,
  status: 'active',
  is_trial: false,
  start_date: '2026-09-01T00:00:00Z',
  end_date: '2026-10-30T00:00:00Z',
  days_left: 30,
  hours_left: 0,
  minutes_left: 0,
  time_left_display: '30 дней',
  traffic_limit_gb: 100,
  traffic_used_gb: 0,
  traffic_used_percent: 0,
  device_limit: 3,
  connected_squads: [],
  servers: [],
  autopay_enabled: false,
  autopay_days_before: 3,
  subscription_url: 'https://example.test/subscription',
  hide_subscription_link: false,
  is_active: true,
  is_expired: false,
  is_limited: false,
};

export const responses = {
  '/api/cabinet/subscription': { has_subscription: true, subscription },
  '/api/cabinet/subscriptions': { subscriptions: [subscription], multi_tariff_enabled: false },
  '/api/cabinet/subscription/devices': { devices: [], total: 0, device_limit: 3 },
  '/api/cabinet/subscription/refresh-traffic': {
    traffic_used_gb: 0,
    traffic_used_percent: 0,
    is_unlimited: false,
  },
  '/api/cabinet/subscription/purchase-options': {
    sales_mode: 'classic',
    balance_kopeks: 20_000,
    periods: [],
    platega_recurrent_enabled: false,
    lava_recurrent_enabled: false,
  },
  '/api/cabinet/subscription/renewal-options': [
    {
      period_days: 30,
      price_kopeks: 50_000,
      price_rubles: 500,
      discount_percent: 0,
      original_price_kopeks: null,
    },
    {
      period_days: 90,
      price_kopeks: 120_000,
      price_rubles: 1200,
      discount_percent: 20,
      original_price_kopeks: 150_000,
    },
  ],
  '/api/cabinet/balance/payment-methods': [
    {
      id: 'test-card',
      name: 'Тестовая карта',
      description: 'Локальный мок',
      min_amount_kopeks: 10_000,
      max_amount_kopeks: 200_000,
      is_available: true,
      quick_amounts: [100_000],
      open_url_direct: false,
    },
  ],
};
